// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/tilemistri/EarningsScreen.tsx": () => import("../components/mockups/tilemistri/EarningsScreen.tsx"),
  "./components/mockups/tilemistri/HomeScreen.tsx": () => import("../components/mockups/tilemistri/HomeScreen.tsx"),
  "./components/mockups/tilemistri/JobsScreen.tsx": () => import("../components/mockups/tilemistri/JobsScreen.tsx"),
  "./components/mockups/tilemistri/LoginOTP.tsx": () => import("../components/mockups/tilemistri/LoginOTP.tsx"),
  "./components/mockups/tilemistri/ProfileSetup.tsx": () => import("../components/mockups/tilemistri/ProfileSetup.tsx"),
  "./components/mockups/tilemistri/SplashWelcome.tsx": () => import("../components/mockups/tilemistri/SplashWelcome.tsx"),
  "./components/mockups/tilemistri/TileMistriGallery.tsx": () => import("../components/mockups/tilemistri/TileMistriGallery.tsx")
};
